// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm_KwmeRzYykX2TH6MqhlO0KYxLjtnpKA',
    appId: '1:865823805566:web:3fa1729b30ae53f62d882f',
    messagingSenderId: '865823805566',
    projectId: 'flutter-test-crud-d5272',
    authDomain: 'flutter-test-crud-d5272.firebaseapp.com',
    storageBucket: 'flutter-test-crud-d5272.firebasestorage.app',
    measurementId: 'G-YY7YN3MXY0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Xo33eNM7gHHJiedRnAwfGSARMq4HClo',
    appId: '1:865823805566:android:df4fac10cb205df82d882f',
    messagingSenderId: '865823805566',
    projectId: 'flutter-test-crud-d5272',
    storageBucket: 'flutter-test-crud-d5272.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqa-BROV4VrWa-kEawbrqp6cmgoSraZ_g',
    appId: '1:865823805566:ios:14fdb9da90f994a62d882f',
    messagingSenderId: '865823805566',
    projectId: 'flutter-test-crud-d5272',
    storageBucket: 'flutter-test-crud-d5272.firebasestorage.app',
    iosBundleId: 'com.codigocaorrecto.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqa-BROV4VrWa-kEawbrqp6cmgoSraZ_g',
    appId: '1:865823805566:ios:14fdb9da90f994a62d882f',
    messagingSenderId: '865823805566',
    projectId: 'flutter-test-crud-d5272',
    storageBucket: 'flutter-test-crud-d5272.firebasestorage.app',
    iosBundleId: 'com.codigocaorrecto.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm_KwmeRzYykX2TH6MqhlO0KYxLjtnpKA',
    appId: '1:865823805566:web:fcc39878aeef72422d882f',
    messagingSenderId: '865823805566',
    projectId: 'flutter-test-crud-d5272',
    authDomain: 'flutter-test-crud-d5272.firebaseapp.com',
    storageBucket: 'flutter-test-crud-d5272.firebasestorage.app',
    measurementId: 'G-81RYFFKXCN',
  );
}